generator:
  num_instances: 5
  base_seed: null
  name_prefix: cfg_seed
  output_dir: act/back_end/examples/nets
  write_manifest: true
  manifest_path: null
  families: [mlp, cnn2d]
  p_mlp: 0.5
  num_classes_choices: [10]
  dtype: torch.float64

mlp:
  input_shapes: [[1, 784], [1, 1, 28, 28]]
  depth_range: [2, 4]
  width_choices: [32, 64, 128]
  activation_choices: [relu, tanh, sigmoid]
  dropout_p_choices: [0.0]
  block_p: 0.6
  block_count_range: [2, 6]
  block_width_choices: [32, 64, 128]
  post_block_activation_p: 0.8

cnn:
  input_shapes: [[1, 1, 28, 28], [1, 3, 32, 32]]
  num_blocks_range: [1, 3]
  channels_choices: [8, 16, 32]
  kernel_choices: [3]
  stride_choices: [1]
  padding_choices: [1]
  use_maxpool_p: 0.3
  fc_hidden_choices: [32, 64, 128]
  activation_choices: [relu, tanh, sigmoid]
  stage_variant_p: 0.5
  stages_range: [1, 3]
  blocks_per_stage_range: [1, 2]
  base_channels_choices: [8, 16, 32]
  channel_mult_choices: [2]
  downsample_choices: [maxpool, avgpool, stride2_conv]
  double_conv_p_choices: [0.5, 0.7]

input_spec:
  kind_choices: [BOX, LINF_BALL]
  p_box: 0.5
  value_range_choices: [[0.0, 1.0]]
  eps_choices: [0.03, 0.05, 0.1]

output_spec:
  kind_choices: [TOP1_ROBUST, MARGIN_ROBUST, LINEAR_LE, RANGE]
  p_top1: 0.5
  margin_choices: [0.0, 0.1, 1.0]
  linear_le_c_range: [-1.0, 1.0]
  linear_le_d_range: [-1.0, 1.0]
  range_choices: [[-1.0, 1.0]]
